### ISSUE TITLE
It's not working on Unity. A lot of components files lost

### ISSUE THREAD

**Issue by redforce01** [GeeTeam/gt3-unity-example#1]
It's not working on Unity. A lot of components files lost

**Comment by redforce01** [comment]
![image](https://user-images.githubusercontent.com/5434149/81533256-da048080-93a0-11ea-8683-9e70bbb3511e.png)

**Comment by NikoXu** [comment]
@redforce01 
Thank for your feedback.
You can delete resource.js from GT3Captcha.bundle manually. I thought it has no effect on the Captcha.

**Comment by redforce01** [comment]
Is there something easy solution for testing ? I wanna using and test geetest in UnityEngine Platform. But It looks like using native code so I am feeling understand how to working it.
my target Platform is mobile(android & iOS). If there is a project that can be driven by testing, I would like help.

**Comment by redforce01** [comment]
I am working on Unity 2017.4.39f1 version. I did delete resource.js file followed your suggestion but it's not working at the start SampleSceneAndroid.
![image](https://user-images.githubusercontent.com/5434149/81667715-93855380-947e-11ea-9d75-e799680c4dc4.png)

**Comment by redforce01** [comment]
I guess it's not working by linked some components in canvas is missing.
![image](https://user-images.githubusercontent.com/5434149/81668053-0f7f9b80-947f-11ea-964d-7110dcd22e42.png)

**Comment by redforce01** [comment]
Help me!
xD

![image](https://user-images.githubusercontent.com/5434149/81668974-6afe5900-9480-11ea-856a-2bb462ff5a0a.png)

**Comment by NikoXu** [comment]
Our Unity Version is 2020.1.0a14 Alpha. You should check it first.

**Comment by NikoXu** [comment]
We support Unity Platform by using a set of native (Android & iOS) lib. The Unity plugin we use as language bridge between C# and native code.

Normally, you import this project into your Unity. Then just build and run it.

**Comment by redforce01** [comment]
now It's working on android build! thx a lot ^^.
but it looks like sometimes failed to show GeeTest. Like this. then keep looping to show"checking". why happen this situation?
![image](https://user-images.githubusercontent.com/5434149/81904766-b179c200-95fe-11ea-8ec8-360ecacde88d.png)
![image](https://user-images.githubusercontent.com/5434149/81904835-cc4c3680-95fe-11ea-83a0-ffc84e7e96c9.png)

I am looking for API guide documents about C#. GeeTest Developer documents has not Unity guide.

**Comment by redforce01** [comment]
I am confused because the different between unity example methods and official site document.
![image](https://user-images.githubusercontent.com/5434149/81908103-c016a800-9603-11ea-899d-8acc03692656.png)

I am watching this page. 
https://docs.geetest.com/captcha/deploy/client/android#Handle-captcha-callback
https://docs.geetest.com/captcha/apirefer/api/android
