### ISSUE TITLE
Is There some way to detect close gt widget by User Back Button or Close Button and set Callback?

### ISSUE THREAD

**Issue by redforce01** [GeeTeam/gt3-unity-example#3]
Is There some way to detect close gt widget by User Back Button or Close Button and set Callback?

It looks like called "onClosed(int num)" when that situation, but I don't understand how to set my callback when it happend

**Comment by mao758444** [comment]
![67cedad0731dd59e5d11035eb5c0e57](https://user-images.githubusercontent.com/39177573/82187507-1bf07200-991f-11ea-8eba-88bf9f46c92a.png)
![9816ca5a4dcce5937f2229195a7670d](https://user-images.githubusercontent.com/39177573/82187528-21e65300-991f-11ea-90e3-3c7cdc10cf6d.png)
https://blog.csdn.net/cym492224103/article/details/39545523

I think you can try it by this

**Comment by mao758444** [comment]
Add a close callback according to this mode
