### ISSUE TITLE
I have some questions. Please help me.

### ISSUE THREAD

**Issue by redforce01** [GeeTeam/gt3-unity-example#4]
In the URLs of api1 and api2 passed to "InitWithAPI"
Is it appropriate to use the ID and key received from the GeeTest Dashboard?

In Example case. 

jo.Call("initWithAPI", "https://www.geetest.com/demo/gt/register-slide-voice", "https://www.geetest.com/demo/gt/validate-slide-voice");

I can't use Geetest server APIs because some issues of my project so 
I want to try sending a POST using ID and Key values to like the above example.

How can I do?
maybe I guess like this In my case?

jo.Call("initWithAPI", "https://www.geetest.com/***********(ID)", "https://www.geetest.com/**********(Key)");

**Comment by mao758444** [comment]
id and key are not used in this way, if you can't use the provided URL, you need to deploy your server with ID and key first, and replace our URL after getting the server URL

You can look at this to understand the process
https://docs.geetest.com/captcha/overview/flowchart

**Comment by redforce01** [comment]
already I saw that documents, but I have to attach geetest without web server. so I am curious how to direct communicate geetest cloud server on client.

**Comment by mao758444** [comment]
As shown in our documentation, the web server is a part of the entire verification process, and it is impossible to do without it

**Comment by redforce01** [comment]
According to the document, we need to communicate twice to use GeeTest, and we are concerned that the part may cause too many load on our WebServer. so we consider to using geetest without webserver.

**Comment by mao758444** [comment]
The design of the entire process is so, you can not do this at present. And the verification service is a lightweight service, I think you can rest assured

**Comment by redforce01** [comment]
As a result we are trying to attaching with WebServer. if we need some help, we would ask again. thank you for answers
